### ISSUE TITLE
libffi error

### ISSUE THREAD

**Issue by capriciousduck** [kurubushi/notion-cli-hs#1]
I've built the binary on Google Cloud shell and transferred the binary to my local machine but I get the following error.

` error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory`

**Comment by kurubushi** [comment]
Sorry for the late reply :bow:

Please install libffi and try that again. This tool (strictly speaking used Haskell libraries) depends on libffi.
For example, if I use in Arch Linux, I install the library with

```bash
pacman -S libffi
```

I'm not famililar with Google Cloud Shell but if it provides apt, you can install with

```bash
apt install libffi-dev
```
