### ISSUE TITLE
Error while making notion-cli

### ISSUE THREAD

**Issue by tukaisg** [kurubushi/notion-cli-hs#3]
I'm getting the below error while making notion-cli :

$ make notion-cli
cabal update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date at index-state 2022-12-22T07:53:18Z
cabal build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: notion-cli-0.1.0.0 (user goal)
[__1] next goal: bytestring (dependency of notion-cli)
[__1] rejecting: bytestring-0.11.3.1/installed-0.11.3.1 (conflict: notion-cli
=> bytestring^>=0.10.12)
[__1] skipping: bytestring-0.11.3.1, bytestring-0.11.3.0, bytestring-0.11.2.0,
bytestring-0.11.1.0, bytestring-0.11.0.0 (has the same characteristics that
caused the previous version to fail: excluded by constraint '^>=0.10.12' from
'notion-cli')
[__1] trying: bytestring-0.10.12.1
[__2] next goal: base (dependency of notion-cli)
[__2] rejecting: base-4.16.4.0/installed-4.16.4.0 (conflict: bytestring =>
base>=4.2 && <4.16)
[__2] skipping: base-4.17.0.0, base-4.16.4.0, base-4.16.3.0, base-4.16.2.0,
base-4.16.1.0, base-4.16.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.2 && <4.16' from
'bytestring')
[__2] rejecting: base-4.15.1.0, base-4.15.0.0, base-4.14.3.0, base-4.14.2.0,
base-4.14.1.0, base-4.14.0.0, base-4.13.0.0, base-4.12.0.0, base-4.11.1.0,
base-4.11.0.0, base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0,
base-4.8.2.0, base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1,
base-4.7.0.0, base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0,
base-4.4.1.0, base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2,
base-4.2.0.1, base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2,
base-3.0.3.1 (constraint from non-upgradeable package requires installed
instance)
[__2] fail (backjumping, conflict set: base, bytestring, notion-cli)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, bytestring, notion-cli

make: *** [Makefile:18: notion-cli] Error 1

**Comment by kurubushi** [comment]
I'm so sorry for my late reply :bow:

With GHC version 9, the dependencies were broken.
I have fixed the dependencies with #4 to solve and build.

Thank you for your telling me :+1:
